dist: trusty

sudo: false

language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- nightly
- hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
      env: YARN_INSTALL=1
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=4.6
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=4.3
    - php: 5.6
      env: WP_VERSION=4.2
    - php: 5.6
      env: WP_VERSION=4.1
    - php: 5.6
      env: WP_VERSION=4.0
    - php: 5.6
      env: WP_VERSION=4.0 COVERAGE=1 GRUNT=1
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  yarn: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

before_install:
  # Install Yarn (https://yarnpkg.com/lang/en/docs/install-ci/#travis-tab)
  - if [ "${YARN_INSTALL}" == "1" ]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash;
      export PATH=$HOME/.yarn/bin:$PATH;
    fi

install:
  # Install Grunt command line interface (https://github.com/gruntjs/grunt-cli).
  - yarn global add grunt-cli
  # Install Node.js packages.
  - yarn install
  # Update Composer itself to the latest version (https://getcomposer.org/doc/03-cli.md#self-update-selfupdate-).
  - composer self-update
  # Install Composer packages.
  - composer install

before_script:
  - wget https://raw.githubusercontent.com/wp-cli/sample-plugin/master/bin/install-wp-tests.sh
  - bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - grunt phpunit
  - grunt phplint
  - if [[ "$GRUNT" == "1" ]]; then grunt; fi

after_success:
  - if [[ '1' == $COVERAGE ]]; then php vendor/bin/coveralls fi
