language: php

php:
    - 5.3
    - 5.4
    - hhvm

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=0
    - WP_VERSION=3.5.1 WP_MULTISITE=1

before_script:
    - composer install
    - wget https://raw.githubusercontent.com/wp-cli/sample-plugin/master/bin/install-wp-tests.sh
    - bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

after_script: php vendor/bin/coveralls
